fanuc:
  # Controller for the real hardware (velocity interface)
  cartesian_velocity_controller_pid:
    type: cartesian_controller/CartesianVelocityControllerPID
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  # Controller for gazebo (velocity interface on top of a position interface)
  cartesian_velocity_controller_pid_sim:
    type: cartesian_controller/CartesianVelocityControllerPIDSim
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link

  # Cartesian state publisher
  cartesian_state_controller:
    type: cartesian_controller/CartesianStateController
    publish_rate: 1000
    root_name: base_link
    tip_name: ee_link
