hardware_control_loop:
  loop_hz: 1000

# Settings for ros_control hardware interface
fanuc_hardware_interface:
  joints: &robot_joints
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

fanuc_cartesian_position_controller:
  type: cartesian_controller/CartesianPositionController
  publish_rate: 1000
  root_name: base_link
  tip_name: tool0

fanuc_cartesian_position_controller_sim:
  type: cartesian_controller/CartesianPositionControllerSim
  publish_rate: 1000
  root_name: base_link
  tip_name: tool0

fanuc_cartesian_state_controller:
  type: cartesian_controller/CartesianStateController
  publish_rate: 1000
  root_name: base_link
  tip_name: tool0

#Publish wrench ----------------------------------
force_torque_sensor_controller:
    type: force_torque_sensor_controller/ForceTorqueSensorController
    publish_rate: 1000
